# Render.com 部署藍圖
# 版本: 1.4 (最終合併版)

services:
  # 服務一：Redis 資料庫
  - name: redis-broker
    type: redis
    plan: free
    ipAllowList: []

  # 服務二：Web 服務 (現在它同時負責 API 和 Worker)
  - name: web-service
    type: web
    plan: free # 免費方案的 Web Service
    env: python
    buildCommand: pip install -r requirements.txt
    # 使用 honcho 根據 Procfile 啟動所有進程
    startCommand: honcho start
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
        